config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :trains
  resources :vans
  resources :railway_stations
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/van.rb
class Van < ApplicationRecord
  TYPE = { CoupeVan: 'Купейный', PlatzVan: 'Плацкартный',
           SleepingVan: 'Спальный', SedentaryVan: 'Сидячий' }.freeze
  VAN_SEATS_KIND = { 'SedentaryVan' => %i[seats],
                'PlatzVan'      => %i[top_seats bottom_seats side_top_seats side_bottom_seats],
                'CoupeVan'      => %i[top_seats bottom_seats],
                'SleepingVan'   => %i[bottom_seats] }.freeze
  PLACES =  { top_seats: 'Верхних', bottom_seats: 'Нижних', side_top_seats: 'Верхних боковых',
              side_bottom_seats: 'Нижних боковых', seats: 'Сидячих' }

  belongs_to :train

  validates :number, uniqueness: { scope: :train_id }
  before_validation :set_seats
  before_save :set_number

  def seats_kind
    VAN_SEATS_KIND[type]
  end

  def show_seats(key)
    PLACES[key]
  end

  def show_self_type
    TYPE[type.to_sym]
  end

  private

  def last_van_number
    train.vans.order(:number).last.number
  end

  def set_number
    self.number ||= 1 if train.vans.count.zero?
    self.number ||= last_van_number + 1 unless train.vans.count.zero?
  end

  def set_seats
    seats_kind.each do |seats|
      send("#{seats}=", 0) if new_record?
    end
  end
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  before_action :set_van, only: %i[show edit update destroy]
  # GET /vans
  def index
    @vans = Van.all
  end

  # GET /vans/1
  def show; end

  # GET /vans/new
  def new
    @van = Van.new
  end

  # GET /vans/1/edit
  def edit; end

  # POST /vans
  def create
    @van = Van.new(van_params)

    if @van.save
      redirect_to vans_path(@van), notice: 'Вагон успешно создан.'
    else
      render :new
    end
  end

  # PATCH/PUT /vans/1
  def update
    if @van.update(van_params)
      redirect_to vans_path(@van), notice: 'Вагон успешно обновлен.'
    else
      render :edit
    end
  end

  # DELETE /vans/1
  def destroy
    @van.destroy
    redirect_to vans_url, notice: 'Вагон удален. Жаль его. Он был так молод...'
  end

  private

  # Use callbacks to share common setup or consvants between actions.
  def set_van
    @van = Van.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def van_params
    params.require(:van).permit(:van_kind_id, :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, :seats, :train_id, :type)
  end


end

app/helpers/vans_helper.rb
module VansHelper
end

app/views/vans/_form.html.erb
<%= form_for(@van.becomes(Van)) do |form| %>
  <%= render 'common/errors', resource: @van %>

  <div class="field">
    <%= form.label :type, 'Выберите тип:' %>
    <%= form.collection_select :type, VanKind.all, :van_type, :title %>
  </div>

  <div class="field">
    <%= form.label :train, 'Выберите поезд:' %>
    <%= form.collection_select :train_id, Train.all, :id, :number %>
  </div>

  <div class="actions">
    <%= form.submit "#{ @van.new_record? ? 'Создать вагон' : 'Изменить вагон'}" %>
  </div>
<% end %>

app/views/vans/_seats.html.erb
<% resource.seats_kind.each do |seats| %>
  <td><%= resource.show_seats(seats) %> мест&nbsp<%= resource.send("#{seats}") %></td>
<% end %>

app/views/vans/_van.html.erb
<tr>
    <% if @train %>
      <td><%= link_to "##{resource.number}", van_path(resource) %></td>
    <% else %>
    <p>
      <td class='actions'><%= link_to 'Показать', van_path(resource) %></td>
      <td class='actions'><%= link_to 'Изменить', edit_van_path(resource) %></td>
      <td class='actions delete'><%= link_to 'Удалить', van_path(resource), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td>Поезд: <%= resource.train.number unless @train %></td>
      <td>Тип: <%= resource.show_self_type %></td>
      <td>#<%= resource.number %></td>
      <td>Места: <%= render 'vans/seats', resource: resource %></td>
    </p>
    <% end %>
</tr>

app/views/vans/edit.html.erb
<h1>Изменить вагон</h1>

<%= form_for(@van.becomes(Van)) do |form| %>
<p><strong>Поезд: </strong><%= @van.train.number %><br />
<strong>Вагон: </strong><%= @van.number %></p>

  <div class="field">
    <%= form.label :kind, 'Выберите тип:' %>
    <%= form.collection_select :type, VanKind.all, :van_type, :title %>
  </div>

  <% @van.seats_kind.each do |seats| %>
    <div class="field">
      <%= form.label seats, @van.show_seats(seats) + ' мест'%>
      <%= form.text_field seats %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit 'Изменить вагон' %>
  </div>
<% end %>

<%= link_to 'Показать', van_path(@van) %> |
<%= link_to 'Назад', vans_path %>

app/views/vans/index.html.erb
<p id="notice"><%= notice %></p>
  <h1>Доступные вагоны:</h1>

  <% if !@vans.count.zero? %>
    <table>
      <thead>
        <tr>
          <th colspan="3">Доступные действия</th>
          <th>Поезд</th>
          <th>Тип</th>
          <th>#</th>
          <th colspan="3">Доступные места в вагоне и их количество</th>
        </tr>
      </thead>

      <tbody><%= render @vans %></tbody>
    </table>
  <% else %>
  <p>Нет доступных вагонов</p>
  <% end %>

  <br>

  <%= link_to 'Создать новый вагон', new_van_path %>

app/views/vans/new.html.erb
<h1>Новый вагон</h1>

<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

app/views/vans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Вагон номер:</strong>
  <%= @van.number %><br />
  <strong>Тип вагона:</strong>
  <%= @van.show_self_type %><br />
  <%= render 'seats', resource: @van %>
</p>

<p>
  <strong>Текущий поезд:</strong>
  <% if @van.train %>
    <%= @van.train.number %>
  <% else %>
    Не указано
  <% end %>
</p>

<%= link_to 'Редактировать', edit_van_path(@van) %>
<%= link_to 'Назад', vans_path %>