config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :trains
  resources :vans
  resources :railway_stations
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :vans

  validates :number, presence: true
  before_save :set_sort_by

  def platz_vans
    vans.where(van_kind: 1)
  end

  def coupe_vans
    vans.where(van_kind: 2)
  end

  def seats(type, kind)
    all = 0
    send("#{type}_vans").each { |van| all += van.send("#{kind}_seats") }
    all
  end

  def set_sort_by
    self.sort_by = 'asc' if new_record?
  end

  def sort_vans
    vans.order(number: sort_by.to_sym)
  end

  # vans collection with uniq values to collection select
  # in show template
  def vans_collection
    collection = []
    vans.map(&:type).uniq.each { |type| collection << [type.to_sym, Van::TYPE[type.to_sym]] }
    collection
  end

  # returns amount of requirement seats
  def adv_info
    seats = places_type_to_more_info.to_sym if places_type_to_more_info
    van = van_type_to_more_info.to_sym if van_type_to_more_info
    van_seats = vans.where(type: van).map(&seats)
    type_mismatch = van_seats.include? nil
    if type_mismatch
      'В вагоне этого типа нет таких мест'
    else
      van_seats.sum
    end
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show; end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit; end

  # POST /trains
  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trains/1
  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_train
    @train = Train.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id, :sort_by, :van_type_to_more_info, :places_type_to_more_info)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_for(@train) do |form| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number, 'Введите номер:' %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div class="field">
    <%= form.label :current_station, 'Назначить станцию:' %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :route, 'Назначить маршрут' %>
    <%= form.collection_select :route_id, Route.all, :id, :title %>
  </div>

  <div class="actions">
    <%= form.submit "#{ @train.new_record? ? 'Создать поезд' : 'Изменить поезд'}" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= train.vans.count %></td>
  <td><%= link_to 'Показать', train %></td>
  <td><%= link_to 'Изменить', edit_train_path(train) %></td>
  <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Показать', @train %> |
<%= link_to 'Назад', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Доступные поезда:</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th>Вагонов</th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Создать новый поезд', new_train_path %>

app/views/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Поезд номер:</strong>
  <%= @train.number %>

  <% if @train.vans.empty? %>
    <br />
    К поезду не присоединены вагоны
  <% else %>
  <br /> 
  <strong>Вагоны:</strong>
  <%= render @train.sort_vans, train: @train %>
    <%= form_for(@train) do |form| %>
      <div><%= form.radio_button(:sort_by, "asc") %>В сторону увеличения
                      <%= form.radio_button(:sort_by, "desc") %>В сторону уменьшения
                      <%= form.submit 'Сортировать' %></div>
    <% end %>
</p>
<p>
    Вы можете указать тип вагона и интересующие Вас места для получения информации о них
    <%= form_for(@train) do |form| %>
      <%= form.label :van_type_to_more_info, 'Выберите тип вагона:' %>
      <%= form.collection_select :van_type_to_more_info, @train.vans_collection, :first, :last %>
      <%= form.label :places_type_to_more_info, 'Выберите тип мест:' %>
      <%= form.collection_select :places_type_to_more_info, SeatsKind.all, :seats_type, :title %>
      <p><%= form.submit 'Найти' %></p>
    <% end %>
    <%= @train.adv_info %>
  <% end %>
</p>
<p>
  <strong>Текущий маршрут:</strong>
  <% if @train.route %>
    <%= @train.route.title %>
  <% else %>
    Нет назначенного маршрута
  <% end %>
  <br />
  <strong>Текущая станция:</strong>
  <% if @train.current_station %>
    <%= @train.current_station.title %>
  <% else %>
    Не указано
  <% end %>
</p>

<%= link_to 'Редактировать', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>