config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :trains
  resources :vans
  resources :railway_stations
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  def station(route)
    RailwayStationsRoute.where(railway_station: self, route: route).first
  end

  def set_index_on(route, index)
    station = station(route)
    station.railway_station_index = index
    station.save if index.is_a? Integer
    raise ArgumentError, 'Индекс не может быть строкой' unless index.is_a? Integer
  end

  def show_index_on(route)
    station = station(route)
    station.railway_station_index
  end
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: %i[show edit update destroy]

  # GET /railway_stations
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  def show; end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit; end

  # POST /railway_stations
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to @railway_station, notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /railway_stations/1
  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station, notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /railway_stations/1
  def destroy
    @railway_station.destroy
    redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/railway_stations/_form.html.erb
<%= form_for(@railway_station) do |form| %>
  <%= render 'common/errors', resource: @railway_station %>
  
  <div class="field">
    <%= form.label :title, 'Введите название станции:' %>
    <%= form.text_field :title, id: :railway_station_title %>
  </div>

  <div class="actions">
    <%= form.submit "#{ @railway_station.new_record? ? 'Создать станцию' : 'Изменить станцию'}" %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Показать', railway_station %></td>
  <td><%= link_to 'Редактировать', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Удалить', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Изменить станцию</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Имеющиеся станции:</h1>

<table>
  <thead>
    <tr>
      <th>Наименование:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'Создать новую станцию', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>Создать новую станцию</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Назад', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Наименование:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p>Станция не входит ни в один маршрут</p>
<% else %>
  <p>Станция входит в следующие маршруты:</p>
  <% @railway_station.routes.each do |s| %>
    <ul>
      <li><%= s.title %></li>
    </ul>
  <% end %>
<% end %>

<%= link_to 'Редактировать', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Назад', railway_stations_path %>